# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f1c1caaa02bb46653a52907f4222e8a10c5cd255afc48ad59c89d4d62661ad08c07db2a80d9d0879d4c749ae4effba2322ea4404060c4efcda8db99a7b7c8d0

test:
  secret_key_base: 761ab8a7f24f4a452070a4111d50cd1e60f9526ae79112eafe1b05842cef231f395968be226bf3cfe2fee1d1adf591e4f0ef8ff9139f7a3ccf40d98f4f0d38a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
